FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
# mcr.microsoft.com/dotnet/framework/sdk --error --docker hub
# mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
WORKDIR /app
ADD ./ /app
# dotnet restore command uses NuGet to restore dependencies as well as project-specific tools
RUN dotnet restore
# Build a project and its dependencies using Release configuration
RUN dotnet build -c Release
# publish your code in release mode and save output to publish directory
RUN dotnet publish -c Release -o /publish   
# COPY . .
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "/app/bin/Release/net5.0/aspnetapp.dll"]


# ms build
# mcr limitations using that image